### ISSUE TITLE
"Smart" backplane for EEM/Kasli ecosystem

### ISSUE THREAD

**Issue by dhslichter** [sinara-hw/DIOT_EEM_Adapter#1]
Moving my comment from #204 to a new issue:

Might it be better in the long haul to have Kasli's functionality actually just integrated on the backplane? You would have a slim "dumb" card that brings SFP and coax connections to the front panel, and connects them to the backplane via some high-performance but lower-pin-count connector, suitable for gigabit signals. Then the Artix FPGA, clock distribution, etc all live on the backplane, and you don't need crazy fat connectors just to route all the EEM signals and clocks off the Kasli and on to the backplane. This would also free more front panel space, because if you are adding 96-DIN mezzanines to Kasli then this obviously will make it wider, which may be undesirable for some.  

The only downside I can see is that if your FPGA on the backplane goes bad for some reason, it's more work to change it out....but this seems like it should not be a very common occurrence.

**Comment by gkasprow** [comment]
@jordens I met a man from Unige at the quantum engineering workshop in London, who is using this Easy-phi stuff. They contacted me and it seems the project is still alive.

**Comment by dtcallcock** [comment]
>  There are other high density connector standards that fit within 4HP. SMB,SMC or micro BNC. We can always use BNC pigtails which can be cheap when ordered in large quantity.

My preference would be to scrap BNC across the whole of Sinara as it's just too big for Eurocard panels IMHO.  If we do that then I think we should pick one connector to replace it (and also replace SMA in some places where high performance isn't required).  

MMCX would be an obvious choice as we are already using it for the Sayma v2 AFE analog inputs and Stabilizer aux digital inputs.  However, they are a bit on the small side and easy to disengage compared SMB/MCX so one might worry about mechanical robustness.  SMC/Micro BNC/LEMO all seem somewhat less ubiquitous and more expensive.  My slight preference would be for MCX, but it would be good to hear from people with more experience.

I'm not totally sure how you would isolate this kind of connector from the front panel though (just a clearance hole?).

Perhaps this should be a separate issue ('[RFC] Death to BNC'?).

**Comment by sbourdeauducq** [comment]
> My preference would be to scrap BNC across the whole of Sinara as it's just too big for Eurocard panels IMHO.

I disagree; many groups have small systems and there is plenty of space for BNCs in a 84hp crate.

Yes, the backplane isn't very interesting and the backward compatibility problems are tough (and what if we need to replace or add a board in an existing EEM system?).

**Comment by dtcallcock** [comment]
Moving BNC discussion to Sampler repository as this is the only board it really effects right away.

**Comment by gkasprow** [comment]
Here is what I mean by Kasli/ Kasli_Zynq cPCIs adapter acting as a system controller.
![obraz](https://user-images.githubusercontent.com/4325054/49547583-59a43b00-f8e3-11e8-8c36-a410c4c6f629.png)
![obraz](https://user-images.githubusercontent.com/4325054/49547605-70e32880-f8e3-11e8-98fb-22c7ec6eabf6.png)


and cPCIs EEM module adapter attached to existing board.
![obraz](https://user-images.githubusercontent.com/4325054/49548145-1c40ad00-f8e5-11e8-87b7-2e9f1163d1ef.png)

**Comment by jordens** [comment]
Yes. Using an existing backplane - CERN or standard - is very valuable.

What minimum number of layers does the connector require on kasli and on the eems?

**Comment by gkasprow** [comment]
I've ordered [this chassis](https://schroff.nvent.com/en/schroff/24579-416). I will make sure the connectors are symmetrical and produce the adapter board.  I will also switch card depth from 160 to 220mm. Guys @CERN claim that it is possible.

**Comment by jordens** [comment]
Nice. The chassis core is just the plain old standard, the front and back rails are with the longer cPCI lips. And the middle rails are movable every 60mm. Get the longer plastic rails, they seem to be available in 220 mm with cPCI coding. I guess you won't have much space in the back anymore which could be a problem for the power connector, the 160 mm power supply might need some hackery to connect the backplane, and the cooling will focus on the front 160 mm.

**Comment by gkasprow** [comment]
I have 80mm on the back - there is space for RTM option.
Supply has dedicated backplane, so we can mount two sets of rails and leave existing plastic rails.
In this way, supply backplane and plastic rails would reside on 160mm rails while rest would be attached to additional rails installed on on 220mm depth.

**Comment by gkasprow** [comment]
Anyway, I will verify it with real HW. Delivery will be within 4 weeks.

**Comment by gkasprow** [comment]
When I look at the crate rear side, the holes seem to be not placed evenly every 60mm
![obraz](https://user-images.githubusercontent.com/4325054/51052556-4d448980-15d7-11e9-8186-fc5284b42671.png)
Anyway, who says we have to use 220mm length?:)

**Comment by gkasprow** [comment]
Some ideas came to my mind. We plan to develop together with the CERN CPCIS controller based on Kasli, but with additional FMC interface and ZynQ. With plugged quad SFP FMC we will get essential Kasli functionality. But we will have to switch to the FFG900 package which means we will have more transceivers (16). 8 GTX will be routed to FMC to enable 8x SFP FMC that already exists. The other 8 GTX can be routed to the backplane. We can reserve some CPCIS slots as DRTIO-capable. And such slots can be equipped with DRTIO-connected modules as well. 
We will also develop 84HP backplane with 8HP slots. We can install DRTIO-capable slots between 8HP slots. In this way, one could combine 8HP modules like Sampler with advanced 4HP DRTIO and standard 4HP EEM modules. Up to 16 various modules could be installed.
Just an idea to discuss.

**Comment by gkasprow** [comment]
@jordens @dtcallcock what do you think about such idea?
I specified it [here](https://github.com/sinara-hw/meta/wiki/Compact-PCI-Serial-EEM-ecosystem)

**Comment by gkasprow** [comment]
Update:
- I agreed with CERN common specification of the open-source backplane. It would be a simple design with necessary signals to use with EEM cards. Boards can be 4HP (with spacers) or 6HP. 2 standard power supplies are supported. CERN will design the radiation hard power supply.
- the backplane can be installed at 160 or 220mm depth
- my CPCIS crate is on a way, I should get it in a few days.
- I'm thinking about a slightly different adapter design that would enable backplane while keeping 160mm card length. The idea is to make 4 adapters:
1. standard with EEM signals
2. active with PCIe or USB bridge so the whole ecosystem of modules could be used natively in CPCIS crate with standard x86 CPU
3. as above but with SpaceWire bridge.
4. simple passive adapter compatible with 220mm assembly

**Comment by gkasprow** [comment]
After a long discussion, we agreed with CERN the specification for the backplane that fulfills all needs.
The contract for backplane design is almost in place.
The board will be designed using Kicad. It will be a simple, low-cost board that fits low-cost chassis but is fully compatible with CPCIS. The slot spacing is 6HP. If there is enough interest, we can make also 4 HP or 8 HP variant since the schematics will be the same.
Btw, a few weeks ago I received my CPCIS crate.

**Comment by gkasprow** [comment]
more or less final component placement. The adapter is mounted on top of Urukul
![obraz](https://user-images.githubusercontent.com/4325054/61183975-6db5d500-a648-11e9-956c-010fab4c545c.png)
![obraz](https://user-images.githubusercontent.com/4325054/61183996-87571c80-a648-11e9-8051-da855859de7d.png)

**Comment by gkasprow** [comment]
Some photos of real HW. The front panel is 3D printed for the moment.
One detail needs fixing - the slot between upper and lower shield.
![2020-06-16 23 32 01](https://user-images.githubusercontent.com/4325054/84835690-6f480400-b034-11ea-819a-6c4bb75ab3b2.jpg)
![2020-06-16 23 32 09](https://user-images.githubusercontent.com/4325054/84835693-71aa5e00-b034-11ea-95a8-aeb479e1d44e.jpg)
![2020-06-16 23 32 17](https://user-images.githubusercontent.com/4325054/84835699-740cb800-b034-11ea-980e-a60f6d973799.jpg)
![2020-06-16 23 32 21](https://user-images.githubusercontent.com/4325054/84835702-75d67b80-b034-11ea-85ff-a3143a70cfa0.jpg)
![2020-06-16 23 32 26](https://user-images.githubusercontent.com/4325054/84835706-7838d580-b034-11ea-8693-08accf6c2c23.jpg)
![2020-06-16 23 32 30](https://user-images.githubusercontent.com/4325054/84835717-7a9b2f80-b034-11ea-910a-c40570536916.jpg)
![2020-06-16 23 32 34](https://user-images.githubusercontent.com/4325054/84835743-8d156900-b034-11ea-96a0-ff4ed52387ab.jpg)
![2020-06-16 23 32 37](https://user-images.githubusercontent.com/4325054/84835744-8e469600-b034-11ea-9141-c69aa7306580.jpg)

**Comment by gkasprow** [comment]
Entire shield/cover is low-cost laser cut. Just a few EUR for set.

**Comment by hartytp** [comment]
Looks lovely! What's the cost of retrofitting that to an EEM? How does that compare to redoing the EEMs as native CPICs (not suggesting we should do that right now, just curious)?

**Comment by hartytp** [comment]
oops, never mind, just saw your previous post. Is all that really just a few EUR? That seems very cheap.

**Comment by gkasprow** [comment]
If we do it as native CPCIS, we would get rid of 4 connectors and 2 standoffs. NRE cost would be also slightly reduced because it would be only one board instead of two. But if we produce the adapters and shields in high quantities, the difference would be negligible. The most expensive are the CPCIS connectors anyway (10 + 9 EUR). I will improve the shield design to eliminate the nasty looking slots and reduce the stress on mezzanine connectors during extraction. The entire stress during insertion is already redirected by the shield.

**Comment by hartytp** [comment]
Cool! It would be awesome to see an ARTIQ crate up and running with CPICS.

**Comment by gkasprow** [comment]
I'm back to business so expect it soon.

**Comment by gkasprow** [comment]
We finished the design of the completely open-source [CPCIS backplane](https://ohwr.org/project/diot-crate-hw/wikis/home) and chassis. It was made with Kicad.  It supports RTM option as well.

**Comment by gkasprow** [comment]
The backplane can easily be tailored to specific use-cases. The same with chassis.

**Comment by marmeladapk** [comment]
Closing - no action needed.
