### ISSUE TITLE
PS_ON# connected to GND

### ISSUE THREAD

**Issue by kaolpr** [sinara-hw/DIOT_EEM_Adapter#12]
This line should be left unconnected.

![image](https://user-images.githubusercontent.com/9166701/146953888-813c3a4f-3d9f-4f17-8799-f623515b8447.png)

**Comment by gkasprow** [comment]
If DIOT specs say so, let's disconnect it.

**Comment by kaolpr** [comment]
Well, DIOT specs is not very elaborate on that matter. However, on DIOT backplane this pin is disconnected. For CPCIs those pins (E2, F2) are marked as reserved. I think it would be better to keep them both disconnected.

**Comment by marmeladapk** [comment]
Now connected to LVDS_15, per new DIOT spec.
