### ISSUE TITLE
DECT_BPR / DECT_RIO

### ISSUE THREAD

**Issue by kaolpr** [sinara-hw/DIOT_EEM_Adapter#14]
I'm not sure if we can connect `DECT_BPR` and `DECT_RIO` to GND. According to note (presumably quote from the CPCIs standard) it is backplane that connects those lines to ground, not peripheral.

![image](https://user-images.githubusercontent.com/9166701/146955933-e2a7d762-6f7d-4633-a842-422ebe09c4ee.png)

Although in DIOT case that won't be a problem, as those lines are connected to GND on DIOT backplane, the same should not be expected from the CPCIs backplanes.

**Comment by gkasprow** [comment]
what DIOT says about it?

**Comment by kaolpr** [comment]
> those lines are connected to GND on DIOT backplane

Guess this feature is not used at all, as I have never heard of any other DIOT backplane.

**Comment by gkasprow** [comment]
RIO is supported by DIOT. DIOT supports only single-star architecture. Some CPCIS backplanes also support full mesh, for Ethernet only. P6 is used for this purpose. The pins are NC at this moment.
