### ISSUE TITLE
SERVMOD is not a negative signal

### ISSUE THREAD

**Issue by marmeladapk** [sinara-hw/DIOT_EEM_Adapter#15]
Remove "_N" from signal name.

**Comment by mkiepiela** [comment]
Not sure. Look at specification ([link](https://ohwr.org/project/diot/wikis/uploads/90afde7824b19862712b9903c5a68e9e/DIOT_system_specification_v2.0-dev-200626.pdf)).

![image](https://user-images.githubusercontent.com/25741678/207035837-39d3ae1a-1715-4081-bb4a-0901b1af90f1.png)

**Comment by marmeladapk** [comment]
See https://ohwr.org/project/diot-pfc-ku/issues/45 and https://ohwr.org/project/diot/issues/7

**Comment by mkiepiela** [comment]
Fixed.
