### ISSUE TITLE
LVDS mux should be controlled by servmod

### ISSUE THREAD

**Issue by marmeladapk** [sinara-hw/DIOT_EEM_Adapter#16]
Controller should be able to switch LVDS lines to alternate mode. I'd like to keep this compliant with specification ([link](https://ohwr.org/project/diot/wikis/uploads/90afde7824b19862712b9903c5a68e9e/DIOT_system_specification_v2.0-dev-200626.pdf)) and consistent with other boards.

**Comment by mkiepiela** [comment]
Controller is able to switch LVDS lines to alternate mode by setting IO expander controlled via I2C in Service Mode.
This solution was chosen together with @kaolpr as more flexible than switching muxes directly by SERVMOD line.
Notice that IO expander has to be controlled anyway (in Service Mode) when accessing the EEPROMs on adapter/EEM0/EEM1.

**Comment by marmeladapk** [comment]
Yes, but this is not compatible with DIOT, so when mixing DIOT cards and cards with adapters you'll have two ways of controlling muxes. IMO it's better to stay consistent on this behaviour.

**Comment by mkiepiela** [comment]
OK, I modified to keep compatibility with DIOT (switching muxes by SERVMOD as default behavior) but have some flexibility as well (possibility of switching muxes by IO expander).
