### ISSUE TITLE
Supply of analog switches

### ISSUE THREAD

**Issue by marmeladapk** [sinara-hw/DIOT_EEM_Adapter#18]
Switches IC1, 5 and 6 are connected to P3V3 instead of P3V3_MP.

IMO it's better to force show supply pins (VCC and GND) on one of the subcomponents and connect supply and gnd explicitly. That way it's easier to spot mistakes like this.

**Comment by mkiepiela** [comment]
Yeah, noticed that when routing PCB.
Fixed. Thanks.
