### ISSUE TITLE
Move mounting holes

### ISSUE THREAD

**Issue by marmeladapk** [sinara-hw/DIOT_EEM_Adapter#25]
By 0.5mm:

![obraz](https://user-images.githubusercontent.com/24512604/210221164-4588c983-25a4-4068-9378-d8a638c0c019.png)

**Comment by filipswit** [comment]
What is the conception of mounting modules? Normally or upside down?

**Comment by gkasprow** [comment]
The concept is to mount them normally using IDC jumper cables.
Native DIOT support will be added in new HW revisions.

**Comment by mkiepiela** [comment]
Done.
