### ISSUE TITLE
Implement JTAG trick from DIOT FMC Carrier

### ISSUE THREAD

**Issue by kaolpr** [sinara-hw/DIOT_EEM_Adapter#9]
Maybe we could implement JTAG trick @marmeladapk implemented in FMC Carrier?

Based on `SERVMOD` state some of the LVDS lines are used to transport JTAG control to the controller module. It could be useful for Phaser / Urukul / Mirny as a remote update path.

**Comment by marmeladapk** [comment]
I guess it should be implemented on each EEM as needed. Also, it's not DIOT specific, we can also use it in old EEM format. We just need a gpio expander with servmod line. I think it should be way faster than updating flash over I2C, as in phaser.

**Comment by kaolpr** [comment]
I agree, however putting it as an assembly variant (we love variants, don't we :heart:) on the adapter we'd avoid creating new revisions for the time being. When all boards are updated we can remove it from the adapter.

BTW, really nice idea ;-).

**Comment by marmeladapk** [comment]
Thanks!

But I don't get how we can implement it on an adapter. We would need a cable from adapter to JTAG connector.

**Comment by kaolpr** [comment]
That's exactly what I was thinking about.

**Comment by marmeladapk** [comment]
@mkiepiela Add reset signal to pin 14 as in digilent hs3.

**Comment by mkiepiela** [comment]
TRSTn added to pin 14..
